---
development:
  cloud_name: dmmx8fllp
  api_key: '957136958239372'
  api_secret: fsDVeIE_O5s5_IZeBqbKIJknfec
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dmmx8fllp
  api_key: '957136958239372'
  api_secret: fsDVeIE_O5s5_IZeBqbKIJknfec
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dmmx8fllp
  api_key: '957136958239372'
  api_secret: fsDVeIE_O5s5_IZeBqbKIJknfec
  enhance_image_tag: true
  static_image_support: false
